manifest:

  defaults:
    revision: v0.2

  remotes:
    # Default ZMK
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # dongle_display
    - name: kiwikey
      url-base: https://github.com/kiwikey

  projects:
    # Default ZMK
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    # dongle_display
    # - name: zmk-dongle-display
      # remote: kiwikey
      # revision: dev_testing01

  self:
    path: config
